#spring:
#  application:
#    name: openzone-message
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/openzone?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  session:
#    store-type: redis
#    timeout: 30m
#  redis:
#    port: 6379
#    host: 192.168.56.10
spring:
  cloud:
    inetutils:
      preferred-networks:
        - 121
    nacos:
      discovery:
        server-addr: 101.43.138.160:8848
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: true  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html


#  rabbitmq:
#    host: 101.43.138.160
#    port: 5672
#    virtual-host: /

#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#server:
#  port: 4988
##日志
#logging:
#  level:
#    com.zms.openzone: error
#    com.alibaba.nacos.client.naming: WARN
#
#url: http://message.lingluan.vip
