#spring:
#  redis:
#    host: 192.168.56.10
#    port: 6379
#    password: JAYlingluan/0118
#  session:
#    store-type: redis
#    timeout: 30m

#youkol:
#  web:
#    kaptcha:
#      config:
#        kaptcha:
#          image:
#            width: 100
#            height: 40
#          textproducer:
#            font:
#              size: 32
#              color: 0,0,0
#            char:
#              string: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
#              length: 4
#          noise:
#            impl: com.google.code.kaptcha.impl.DefaultNoise
#
#url: http://auth.openzone.com
#feign:
#  client:
#    config:
#      default:
#        read-timeout: 600000
#        connect-timeout: 600000
