#spring:
#  application:
#    name: openzone-member
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/openzone?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  session:
#    store-type: redis
#    timeout: 30m
#  redis:
#    port: 6379
#    host: 192.168.56.10
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#
#
#
#  #邮箱
#  mail:
#    host: smtp.qq.com
#    port: 465
#    username: 1129136596@qq.com
#    password: awdxkgoborazfijh
#    protocol: smtps
#server:
#  port: 1988
##日志
#logging:
#  level:
#    com.zms.openzone: error
#    com.alibaba.nacos.client.naming: WARN
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#community:
#  path:
#    domain: http://localhost:8888
#    upload: E:/博客/JAVA/项目/community/upload
#
#openzone:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10
#feign:
#  client:
#    config:
#      default:
#        read-timeout: 600000
#        connect-timeout: 600000
